# H2 ?????? ?? ?? (??? DB)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 DB ?? ?? (Datasource)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ?? ???? DB? ??
spring.session.store-type=jdbc

# JPA / Hibernate ?? (DB ?? ??)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ??? ?? (?? ?? ??)
spring.mustache.charset=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# OAuth ?? ?? ??
spring.profiles.include=oauth

