# H2 데이터베이스 콘솔 설정 (테스트 DB)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 DB 연결 설정 (Datasource)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 세션 저장소를 DB로 설정
spring.session.store-type=jdbc

# JPA / Hibernate 설정 (DB 접근 관련)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 문자셋 설정 (한글 깨짐 방지)
spring.mustache.charset=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# OAuth 설정 파일 포함
spring.profiles.include=oauth
